overview:
  title: External Buttons
  image: logo.png
  description: Shows how product zoom with FSI Viewer and external minimalist buttons used looks.
  order: 5
  facts:
    - JS built FSI Viewer
    - external UI
    - zoom and pan
schema: bootstrap-taupe
sample:
  menu:
    data: clothing-menu.yml
  featured:
    data: clothing-featured.yml
  highlight: DEAL OF THE DAY
  footer:
    credits:
      photos:
        - author: Kate Skumen
          link: https://unsplash.com/@skumen?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
          platform: Unsplash
      viewer:
        link: https://www.neptunelabs.com/fsi-viewer/
  hero: false
  fsi:
    viewer: true
  bootstrap:
    icons: true
  jquery: true
