overview:
  title: React Test
  image: logo.png
  description: React
  order: 2
  facts:
    - XXX
sample:
  template:
    schema: react-taupe
    components:
      fsi:
        viewer: true
      react:
        theme: data/clothing.yml
        data:
          credits:
            photos:
              - author: Artem Bondarchuk
                link: https://unsplash.com/@artembondarchuk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
                platform: Unsplash
            viewer:
              link: https://www.neptunelabs.com/fsi-viewer/
      bootstrap:
        icons: true
