overview:
  title: External Slider
  image: logo.png
  description: Shows how a zoom with FSI Viewer and external slider used could look.
  order: 4
  facts:
    - JS built FSI Viewer
    - external slider
    - zoom and pan
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      highlight: DEAL OF THE DAY
      featured: true
      footer: true
      fsi:
        viewer: true
      bootstrap:
        icons: false
      jQuery: true
  mapping:
    html: "external.html"
    css: "external.css"
    js: "external.js"
jsfiddle:
  deploy: true

