title: External Slider
image: logo.png
description: Shows how a zoom with FSI Viewer and external slider used could look.
priority: 4
facts:
  - JS built FSI Viewer
  - external slider
  - zoom and pan
jsfiddle:
  mapping:
    html: "index.html"
    css: "external.css"
    js: "external.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/touchzoom/js/fsitouchzoom.js"
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@{{dependencies.bootstrapIcons}}/font/bootstrap-icons.css
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/viewer/js/fsiviewer.js"
    - https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js
