overview:
  title: Detail Page (JSON) TBD
  image: logo.png
  description: PDP with FSI Viewer and articles build from JSON.
  facts:
    - JS built FSI Viewer
    - zoom and pan
    - article implementation with JSON
  order: 6
sample:
  template:
    schema: framework-2023
    components:
        menu:
          template: data/clothing-menu.yml
        highlight: DEAL OF THE DAY
        footer:
          credits:
            photos:
              - author: Kate Skumen
                link: https://unsplash.com/@skumen?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
                platform: Unsplash
            viewer:
              link: https://www.neptunelabs.com/fsi-viewer/
        fsi:
          viewer: true
        bootstrap:
          icons: true
  mapping:
    html: "index.html"
    js: "pdp.js"
    css: "pdp.css"
jsfiddle:
  deploy: true
