title: Product Detail Page
image: logo.png
description: PDP with FSI Viewer and articles build from JSON.
facts:
  - JS built FSI Viewer
  - zoom and pan
  - article implementation with JSON
priority: 4
