title: Product Detail Page (JSON)
image: logo.png
description: PDP with FSI Viewer and articles build from JSON.
facts:
  - JS built FSI Viewer
  - zoom and pan
  - article implementation with JSON
priority: 6
jsfiddle:
  mapping:
    html: "index.html"
    js: "pdp.js"
    css: "pdp.css"
  resources:
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@{{dependencies.bootstrapIcons}}/font/bootstrap-icons.css
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/viewer/js/fsiviewer.js"
