overview:
  title: Detail Page (JSON) TBD
  image: logo.png
  description: PDP with FSI Viewer and articles build from JSON.
  facts:
    - JS built FSI Viewer
    - zoom and pan
    - article implementation with JSON
  order: 6
sample:
  template:
    schema: framework-2023
    components:
        menu:
          template: data/clothing-menu.yml
        highlight: DEAL OF THE DAY
        footer: true
        fsi:
          viewer: true
        bootstrap:
          icons: false
  mapping:
    html: "index.html"
    js: "pdp.js"
    css: "pdp.css"
jsfiddle:
  deploy: true
