title: Simple Viewer
image: logo.png
description: This demo shows a simple viewer.
priority: 1
jsfiddle:
  mapping:
    html: "index.html"
    css: "pdp.css"
    js: "pdp.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/viewer/js/fsiviewer.js"

