overview:
  title: No Interface Version
  image: logo.png
  description: Shows how a simple no interface product zoom version looks.
  order: 3
  facts:
    - JS built FSI Viewer
    - zoom and pan
    - minimalist no interface version
schema: bootstrap-taupe
sample:
  menu:
    data: clothing-menu.yml
  highlight: DEAL OF THE DAY
  footer:
    credits:
      photos:
        - author: Kate Skumen
          link: https://unsplash.com/@skumen?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
          platform: Unsplash
      viewer:
        link: https://www.neptunelabs.com/fsi-viewer/
  fsi:
    viewer: true
  bootstrap:
    icons: true
