overview:
  title: Starter
  image: logo.png
  description: Start your own demo
  order: 99
sample:
  template:
    schema: vanilla
  mapping:
    html: 'index.html'
    js: 'script.js'
    css: 'style.css'
