overview:
  title: Simple Product Zoom
  image: logo.png
  description: Shows how a simple product detail page could look with FSI Viewer used.
  order: 1
  facts:
    - JS built FSI Viewer
    - zoom and pan
    - plain menu
sample:
  template:
    schema: framework-furniture
    components:
      menu: true
      highlight: false
      featured: true
      categories: true
      footer: true
      hero: false
      fsi:
        viewer: true
        touchZoom: true
      bootstrap:
        icons: true
  mapping:
      html: "detail.html"
      css: "detail.css"
      js: "detail.js"
jsfiddle:
  deploy: true
