overview:
  title: Simple Product Zoom
  image: logo.png
  description: Shows how a simple product detail page could look with FSI Viewer used.
  order: 1
  facts:
    - JS built FSI Viewer
    - zoom and pan
    - plain menu
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/clothing-menu.yml
      highlight: DEAL OF THE DAY
      featured:
        template: data/clothing-featured.yml
      footer: true
      fsi:
        viewer: true
        touchZoom: true
      bootstrap:
        icons: true
  mapping:
      html: "detail.html"
      css: "detail.css"
      js: "detail.js"
jsfiddle:
  deploy: true
