overview:
  title: Product Zoom (Modal)
  image: logo.png
  description: Shows how a simple product detail page with an integrated modal could look.
  order: 2
  facts:
    - JS built FSI Viewer
    - zoom and pan
    - modal implementation
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/furniture-menu.yml
      highlight: HIGHLIGHT OF THE DAY
      featured:
        template: data/furniture-featured.yml
      categories: true
      footer: true
      hero: false
      fsi:
        viewer: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    css: "modal.css"
    js: "modal.js"
jsfiddle:
  deploy: true
