overview:
  title: External Buttons
  image: logo.png
  description: Shows how product zoom could look with FSI Viewer and external minimalist buttons used.
  order: 5
  facts:
    - JS built FSI Viewer
    - external UI
    - zoom and pan
sample:
  template:
    schema: framework-furniture
    components:
      menu: true
      highlight: HIGHLIGHT OF THE DAY
      featured: true
      categories: true
      footer: true
      hero: false
      fsi:
        viewer: true
      bootstrap:
        icons: true
      jquery: true
  mapping:
    html: "external-buttons.html"
    css: "external-buttons.css"
    js: "external-buttons.js"
jsfiddle:
  deploy: true
